package com.AppReclamos.AppReclamosCms.Modelos.Enums;

public enum ComunicacionResultado {
    DOMICILIO_CONSIGNADO_LIBRO_RECLAMACIONES,
    CORREO_ELECTRONICO,
    OTRA_DIRECCION_PROPORCIONADA_POR_EL_USUARIO,
    NOTIFICACION_POR_EL_USUARIO_EN_EL_LIBRO_RECLAMACIONES,
    TELEFONO_ACREDITADO_POR_EL_USUARIO,
    NO_SE_LOGRA_NOTIFICAR_DEBIDO_A_IMPRECISIONES_EN_DIRECCION_CORREO_ATRIBUIBLES_USUARIO;
}
