package com.AppReclamos.AppReclamosCms.Modelos.Enums;

public enum GestionServicios {
    CONSULTA_EXTERNA,
    HOSPITALIZACION,
    EMERGENCIA,
    CENTRO_QUIRURGICO,
    CENTRO_OBSTETRICO,
    UCI_UCIN,
    FARMACIA,
    SERVICIOS_MEDICOS_APOYO,
    ATENCION_DOMICILIO_AMBULATORIA,
    ATENCION_DOMICILIO_URGENCIA,
    OFICINAS_ADMINISTRATIVAS,
    INFRAESTRUCTURA,
    REFERENCIA_CONTRAREFERENCIA;
}
